import { intro, outro, text, confirm, password, log as clackLog, isCancel, cancel } from '@clack/prompts';
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { randomBytes } from 'node:crypto';

const ENV_FILE = 'pypes.env';
const DATA_DIR = 'pypes-data';

export async function init(): Promise<void> {
  intro('pypes-bot setup');

  if (!(await ensureDocker())) return;

  if (existsSync(ENV_FILE)) {
    const overwrite = await confirm({ message: `${ENV_FILE} already exists. Overwrite?`, initialValue: false });
    if (isCancel(overwrite) || !overwrite) {
      cancel('Aborted.');
      return;
    }
  }

  clackLog.info('You can find your Slack tokens at https://api.slack.com/apps/your-app');

  const signingSecret = await ask(password({ message: 'Slack signing secret' }));
  const botToken = await ask(
    password({
      message: 'Slack bot token (xoxb-...)',
      validate: (v) => (v.startsWith('xoxb-') ? undefined : 'expected xoxb-...'),
    }),
  );
  const allowedUsers = await ask(
    text({
      message: 'Allowed Slack user IDs (comma-separated, e.g. U07ABC,U09XYZ)',
      validate: (v) => (v.trim().length > 0 ? undefined : 'at least one required'),
    }),
  );
  const allowedChannels = await ask(
    text({
      message: 'Allowed Slack channel IDs (comma-separated)',
      validate: (v) => (v.trim().length > 0 ? undefined : 'at least one required'),
    }),
  );

  clackLog.info('GitHub PAT must be fine-grained, single-repo, with Actions/Contents/PRs write.');
  const ghPat = await ask(password({ message: 'GitHub fine-grained PAT' }));
  const ghRepo = await ask(
    text({
      message: 'GitHub repo (owner/repo)',
      validate: (v) => (/^[^/]+\/[^/]+$/.test(v.trim()) ? undefined : 'expected owner/repo'),
    }),
  );

  clackLog.warn(
    'Anthropic key reminder: use a DEDICATED key with a $X/mo console spend cap. Do not reuse your main key.',
  );
  const anthropicKey = await ask(password({ message: 'Anthropic API key' }));

  const publicUrl = await ask(
    text({
      message: 'Public HTTPS URL of this bot (cloudflared/ngrok)',
      placeholder: 'https://xxxxx.trycloudflare.com',
      validate: (v) => (/^https:\/\//.test(v.trim()) ? undefined : 'must be https://'),
    }),
  );

  const callbackSecret = randomBytes(32).toString('hex');

  const envLines = [
    '# Generated by `npx @pypes/bot init`',
    '',
    '# Slack',
    `SLACK_SIGNING_SECRET=${signingSecret}`,
    `SLACK_BOT_TOKEN=${botToken}`,
    `PYPES_ALLOWED_USER_IDS=${allowedUsers}`,
    `PYPES_ALLOWED_CHANNELS=${allowedChannels}`,
    '',
    '# GitHub',
    `PYPES_GH_PAT=${ghPat}`,
    `PYPES_GH_REPO=${ghRepo}`,
    'PYPES_GH_WORKFLOW=pypes-bot-autopilot.yaml',
    'PYPES_GH_REF=main',
    '',
    '# Runner callback',
    `PYPES_RUNNER_CALLBACK_SECRET=${callbackSecret}`,
    `PYPES_PUBLIC_URL=${publicUrl}`,
    '',
    '# Anthropic (for intent classifier)',
    `ANTHROPIC_API_KEY=${anthropicKey}`,
    '',
    '# Defaults — adjust if you like',
    'PYPES_DAILY_BUDGET_USD=50',
    'PYPES_MAX_BUDGET_USD=10',
    'PYPES_MAX_TURNS=15',
    'PYPES_CLAUDE_MODEL=haiku',
    '',
    'DATABASE_PATH=/data/pypes.db',
    'PORT=8080',
  ].join('\n');

  writeFileSync(ENV_FILE, envLines, { mode: 0o600 });
  if (!existsSync(DATA_DIR)) mkdirSync(DATA_DIR);

  outro(`Wrote ${ENV_FILE} and ${DATA_DIR}/`);

  console.log('\nNext steps:');
  console.log(`  1. Start the bot:           npx @pypes/bot start`);
  console.log(`  2. In your Slack app, set the Event Subscriptions Request URL to:`);
  console.log(`                              ${publicUrl}/slack/events`);
  console.log(`  3. In your GitHub repo:`);
  console.log(`     - Copy docs/pypes-bot-autopilot.yaml → .github/workflows/`);
  console.log(`     - Add repo secrets:`);
  console.log(`         ANTHROPIC_API_KEY            (your dedicated capped key)`);
  console.log(`         PYPES_SLACK_BOT_TOKEN         (xoxb-...)`);
  console.log(`         PYPES_GH_PAT                  (same PAT)`);
  console.log(`         PYPES_RUNNER_CALLBACK_SECRET  ${callbackSecret}`);
  console.log(`         PYPES_PUBLIC_URL              ${publicUrl}`);
  console.log();
}

async function ensureDocker(): Promise<boolean> {
  try {
    const res = Bun.spawnSync(['docker', '--version'], { stdout: 'pipe', stderr: 'pipe' });
    if (res.exitCode === 0) return true;
  } catch {
    // fall through
  }
  console.error('Docker is required but not found. Install Docker first: https://docs.docker.com/get-docker/');
  return false;
}

async function ask<T>(p: Promise<T | symbol>): Promise<string> {
  const v = await p;
  if (isCancel(v)) {
    cancel('Cancelled.');
    process.exit(1);
  }
  return String(v).trim();
}
